- name: Checkout
  uses: actions/checkout@v3.5.2
  
- name: Checkout
  uses: actions/checkout@v3.5.2
  with:
    repository: mtararujs/python-greetings
    path: python-greetings
      
- name: Install pip dependencies
  run: |
    cd python-greetings
    pip3 install -r requirements.txt
